AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - "lib/yard-sig.rb"

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
